// Generated by resMaker

#ifndef _Assets_H
#define _Assets_H

#define kMeshesMoto    0
#define kTexturesGui    1
#define kTexturesSkyPos_X    2
#define kTexturesSkyNeg_Z    3
#define kTexturesSkyPos_Z    4
#define kTexturesSkyNeg_Y    5
#define kTexturesSkyPos_Y    6
#define kTexturesSkyNeg_X    7
#define kTexturesWall1    8
#define kTexturesMoto    9


#endif // _Assets_H